#!/bin/sh
BGO_DISABLE_PROJECT_DETECT=1
export BGO_DISABLE_PROJECT_DETECT

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address --full /process/999

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address --full /process/999/map/0

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address-edit process/999/0x04 | bin/bgo address --full /process/999/address/0x04

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address-edit -c 'stupid comment' process/999/map/0/address/0x04 | bin/bgo address --full /process/999/map/0/0x04/revision/0

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address-edit -c 'stupid comment' process/999/map/0/address/0x04 | bin/bgo address --full /process/999/map/0/0x04/revision/0

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0 -s 2 process/999 | bin/bgo address-create -a 2 -s 1 process/999 | bin/bgo address-create -a 3 -s 1 process/999 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address-edit -c 'stupid comment' process/999/map/0/address/0x04 | bin/bgo address-delete process/999/map/0/address/0x03 | bin/bgo address --full /process/999/map/0

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0 -s 2 process/999 | bin/bgo address-create -a 2 -s 1 process/999 | bin/bgo address-create -a 3 -s 1 process/999 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address-edit -c 'stupid comment' process/999/map/0/address/0x04 | bin/bgo revision-create -c 'simple revision' process/999/map/0 | bin/bgo address-create -a 0 -s 6 -r 1 process/999 | bin/bgo address --full /process/999/map/0/revision/1

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0 -s 2 process/999 | bin/bgo address-create -a 2 -s 1 process/999 | bin/bgo address-create -a 3 -s 1 process/999 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address-edit -c 'stupid comment' process/999/map/0/address/0x04 | bin/bgo revision-create -c 'simple revision' process/999/map/0 | bin/bgo address-create -a 0 -s 6 -r 1 process/999 | bin/bgo revision --full /process/999/map/0/revision/1

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0 -s 2 process/999 | bin/bgo address-create -a 2 -s 1 process/999 | bin/bgo address-create -a 3 -s 1 process/999 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address-edit -c 'stupid comment' process/999/map/0/address/0x04 | bin/bgo revision-create -c 'simple revision' process/999/map/0 | bin/bgo address-create -a 0 -s 6 -r 1 process/999 | bin/bgo revision -l /process/999/map/0/revision/1

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0 -s 2 process/999 | bin/bgo address-create -a 2 -s 1 process/999 | bin/bgo address-create -a 3 -s 1 process/999 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address-edit -c 'stupid comment' process/999/map/0/address/0x04 | bin/bgo revision-create -c 'simple revision' process/999/map/0 | bin/bgo address-create -a 0 -s 6 -r 1 process/999 | bin/bgo revision --full /process/999/map/0

bin/bgo process-create -i 999 -f ^bin^ls /bin/ls stuff | bin/bgo process-edit -f /bin/ls -C 'ls -l' -c 'stuff' 999 | bin/bgo map-create -s 100 process/999 | bin/bgo map-edit -f 'rwx' -c 'oog' process/999/map/0 | bin/bgo address-create -a 0 -s 2 process/999 | bin/bgo address-create -a 2 -s 1 process/999 | bin/bgo address-create -a 3 -s 1 process/999 | bin/bgo address-create -a 0x04 -s 16 process/999 | bin/bgo address-edit -c 'stupid comment' process/999/map/0/address/0x04 | bin/bgo revision-create -c 'simple revision' process/999/map/0 | bin/bgo address-create -a 0 -s 6 -r 1 process/999 | bin/bgo revision --full /process/999

