#!/bin/sh
# Copyright 2013 Thoughtgang <http://www.thoughtgang.org>
# Generate a BGO Project from binaries in tests/targets.
# This project can be used for testing utilities, applications, and such.
# NOTE: Project will be created as 'project.bgo' in the current directory
#       if a path is not specified.

PATH="./bin:$PATH"
PROJECT_PATH=$1
[ -z "$PROJECT_PATH" ] && PROJECT_PATH='project.bgo'
echo Using project path \'$PROJECT_PATH\'...
[ -e "$PROJECT_PATH" ] && echo 'Project exists! Exiting.' && exit 1
[ -e "tests/targets" ] || (echo "Cannot find dir 'tests/targets'." && exit 1)

echo Creating project using \'bgo target-disasm\'...
bgo target-disasm -p "$PROJECT_PATH" tests/targets/linux-2.6.x-64.* | \
bgo project-edit -d 'An autogenerated project for testing BGO applications' | \
bgo tag / linux demo qa |\
bgo tag file/tests^targets^linux-2.6.x-64.bin linux elf executable x86_64 |\
bgo tag file/tests^targets^linux-2.6.x-64.so linux elf shared_library x86_64 |\
bgo comment / comment in standard context by default author |\
bgo comment -a edf -c todo / Add more authors and comments |\
bgo comment -a edf -c doc / This project is for testing BGO applications |\
bgo properties / version=1.01-test coords='{"x":0,"y":0}' vals='[1,2,3]' |\
bgo pipeline-eval '$BgoState.project.properties[:command_history] = $BgoState.command_history; $BgoState.project.update'

echo Done.
